# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
# bundler_args: --binstubs

# Specify which versions of Ruby to run the tests on; each version will be used
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - jruby-19mode
  - rbx-19mode
  - ruby-head


before_script:
  - sh -e /etc/init.d/xvfb start

env: "SKIP_WEBGL=1 "

# JRuby and RBX are not yet officially supported,
# until failing dependencies work properly or are
# no longer depended upon.
matrix:
  allow_failures:
    # disabled ruby-head for now since redcloth doesn't install
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-19mode
