class Jax.Mesh.LineCube extends Jax.Mesh.Lines
  constructor: (@halfSize = 0.5, @offset = [0,0,0]) ->
    if typeof @halfSize isnt 'number'
      super @halfSize
      @halfSize = @size / 2
    else
      super()
  
  init: (vertices, colors, normals, textures, indices) ->
    halfSize = @halfSize
    offset = @offset
    
    v = vec3.create()
    # left quad
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1, 1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1, 1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1, 1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1,-1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1,-1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1,-1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1,-1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1, 1, 1]))...
    # right quad
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1, 1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1, 1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1, 1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1,-1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1,-1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1,-1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1,-1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1, 1, 1]))...
    # front horizontal
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1, 1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1, 1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1,-1, 1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1,-1, 1]))...
    # back horizontal
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1, 1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1, 1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [-1,-1,-1]))...
    vertices.push vec3.add(offset, vec3.scale(halfSize, [ 1,-1,-1]))...

    true
